# Generated by Django 5.2 on 2025-04-25 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('received', 'Received')], default='ordered', max_length=20)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.part')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_order_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
