# Generated by Django 5.2 on 2025-05-11 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('license_plate', models.CharField(max_length=15, unique=True, verbose_name='Госномер')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN-код')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег (км)')),
                ('last_service', models.DateField(verbose_name='Последнее ТО')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Рыночная цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
            },
        ),
    ]
