# Generated by Django 5.2 on 2025-05-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('hatchback', 'Хэтчбек'), ('coupe', 'Купе'), ('minivan', 'Минивэн')], default='sedan', max_length=20, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
