# Generated by Django 5.2 on 2025-05-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(blank=True, choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('hatchback', 'Хэтчбек'), ('coupe', 'Купе'), ('minivan', 'Минивэн')], default='sedan', max_length=20, null=True, verbose_name='Категория'),
        ),
    ]
